export const STORE_KEYS_CONSTANTS = {
  PS_LOGGED_USER: 'PS_USER',
  PS_PRODUCTS: 'PS_PRODUCTS',
  PS_SHOPS: 'PS_SHOPS',
  PS_SHOPS_PRODUCTS: 'PS_SHOPS_PRODUCTS',
  PS_FAVOURITE_SHOPS: 'PS_FAVOURITE_SHOPS',
  PS_FAVOURITE_PRODUCTS: 'PS_FAVOURITE_PRODUCTS',
  PS_SHOPPING_CART: 'PS_SHOPPING_CART',
  PS_APP_LANGUAGE: 'PS_APP_LANGUAGE',
  PS_USER_ALERTS: 'PS_USER_ALERTS',
  PS_LAST_SHOP_ID: 'PS_LAST_SHOP_ID'
};
